from knowledge.courses.base import CourseProfile


# 中山競馬場は右回りで直線が短く、最後に急坂があります。
# 東京のような長い直線の瞬発力だけではなく、位置取り・器用さ・持続力・坂対応を重視します。
NAKAYAMA_BASIC_FEATURES = [
    "右回り",
    "小回り寄り",
    "直線が短い",
    "最後に急坂がある",
    "コーナー4回のコースが多い",
    "位置取りと立ち回りが重要",
]

NAKAYAMA_TURF_COMMON = [
    "芝1200mは外回り短距離でスピードと急坂対応を評価",
    "芝1600mは外回りで枠順と位置取りが重要",
    "芝1800mから2500mはコーナー4回で器用さと持続力を評価",
    "最後の急坂で脚が止まらないパワーと持続力を重視",
]

NAKAYAMA_DIRT_COMMON = [
    "ダート1200mはテンの速さと先行力が重要",
    "ダート1800mはコーナー4回で先行力・持続力・パワーを評価",
    "ダート2400mはスタミナとロングスパート性能を評価",
    "砂をかぶっても崩れない馬群対応力も重要",
]

NAKAYAMA_AI_POLICY = [
    "東京よりも位置取りと立ち回りを重視する",
    "最後の急坂をこなすパワーと持続力を評価する",
    "短い直線のため後方一気は展開待ちとして扱う",
    "開幕週は内前、開催後半や馬場悪化時はパワー型・差しの浮上を確認する",
]


NAKAYAMA_COURSE_PROFILES = {
    ("中山", "芝", 1200): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=1200,
        features=["外回り短距離", "スタート後は下り基調", "最後に急坂", "スピードと坂対応が重要"],
        favorable_styles=["逃げ", "先行", "好位差し"],
        frame_bias="内から中枠を評価。外枠はテンに速く位置を取れる馬なら対応可能。",
        required_abilities=["テンの速さ", "先行力", "スピード持続力", "急坂対応", "右回り適性"],
        cautions=["後方一気、スタートが遅い馬、平坦専用のスピード型は割引。"],
        course_shape="中山芝1200m。下りでスピードに乗りやすいが、最後の急坂で止まらない力が必要。",
        pace_tendency="ハイペースになりやすい。開幕週は前残り、差し馬場なら好位差しも浮上。",
        closing_tendency="基本は逃げ・先行有利。ハイペース時は坂で止まらない差しを評価。",
        suitable_types=["芝1200m実績馬", "テンが速い馬", "急坂で止まらない馬", "中山芝実績馬"],
        unsuitable_types=["後方一気型", "スタート不安", "平坦専用型", "坂で甘くなる馬"],
        bloodline_tendency=["ロードカナロア系", "ダイワメジャー系", "モーリス系", "ミッキーアイル系"],
        score_modifiers={
            "early_speed": 3,
            "sustained_speed": 2,
            "hill_power": 2,
            "right_turn": 2,
            "inside_draw": 1,
            "late_speed": -1,
        },
    ),
    ("中山", "芝", 1600): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=1600,
        features=["外回りマイル", "スタート後すぐコーナー", "枠順と位置取りが重要", "最後に急坂"],
        favorable_styles=["先行", "好位差し", "差し"],
        frame_bias="内枠を評価。外枠は序盤に外を回されやすく、位置取り能力が必要。",
        required_abilities=["先行力", "立ち回り", "マイル適性", "急坂対応", "右回り適性", "持続力"],
        cautions=["外枠で位置を取れない馬、東京向きの大外一気型、折り合い不安は割引。"],
        course_shape="中山芝1600m。外回りだが序盤のコーナーまでが短く、枠順と位置取りが重要。",
        pace_tendency="平均からやや速めになりやすい。スローなら前、流れれば好位差しと差しを評価。",
        closing_tendency="直線だけの切れ味より、コーナーから加速して坂を上がる持続力を評価。",
        suitable_types=["中山マイル実績馬", "内枠で立ち回れる馬", "好位から脚を使える馬"],
        unsuitable_types=["外枠で位置取りが苦手な馬", "大箱専用の差し馬", "坂で止まる馬"],
        bloodline_tendency=["ダイワメジャー系", "ロードカナロア系", "モーリス系", "キズナ系"],
        score_modifiers={
            "positioning": 3,
            "inside_draw": 3,
            "mile_fit": 2,
            "hill_power": 2,
            "right_turn": 2,
            "outside_draw": -2,
        },
    ),
    ("中山", "芝", 1800): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=1800,
        features=["内回り寄り", "コーナー4回", "スタート後すぐ坂", "器用さと持続力が重要"],
        favorable_styles=["先行", "好位差し", "逃げ", "差し"],
        frame_bias="内から中枠を評価。外枠は早めに位置を取れる機動力が必要。",
        required_abilities=["立ち回り", "コーナリング", "持続力", "急坂対応", "中距離適性"],
        cautions=["大外一気型、東京外回り専用型、コーナーで置かれる馬は割引。"],
        course_shape="中山芝1800m。コーナー4回で立ち回りと持続力が問われる。",
        pace_tendency="スローから平均が多い。早めに動く馬がいると持続戦。",
        closing_tendency="直線だけで差すより、好位から長く脚を使う形を評価。",
        suitable_types=["中山芝1800m実績馬", "小回り中距離で好走する馬", "好位で運べる馬"],
        unsuitable_types=["大箱専用型", "後方一気型", "コーナー加速が苦手な馬"],
        bloodline_tendency=["キズナ系", "エピファネイア系", "モーリス系", "ハーツクライ系"],
        score_modifiers={
            "positioning": 3,
            "cornering": 3,
            "sustained_speed": 3,
            "hill_power": 2,
            "right_turn": 2,
            "late_speed_only": -2,
        },
    ),
    ("中山", "芝", 2000): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=2000,
        features=["内回り", "コーナー4回", "皐月賞の舞台", "機動力と持続力が重要"],
        favorable_styles=["先行", "好位差し", "差し", "まくり"],
        frame_bias="内から中枠を評価。外枠は早めに動ける持続力が必要。",
        required_abilities=["中距離適性", "立ち回り", "持続力", "急坂対応", "ロングスパート", "右回り適性"],
        cautions=["東京芝2000m専用型、後方一気、瞬発力だけの馬は割引。"],
        course_shape="中山芝2000m。コーナー4回で機動力と持続力が問われる代表的な中距離コース。",
        pace_tendency="平均ペースから持続戦になりやすい。スローでも早めに動ける馬を評価。",
        closing_tendency="直線が短いため、早めに進出して坂で踏ん張れる馬を評価。",
        suitable_types=["中山芝2000m実績馬", "皐月賞型の機動力がある馬", "小回り中距離に強い馬"],
        unsuitable_types=["瞬発力だけの馬", "後方一気型", "コーナーで動けない馬"],
        bloodline_tendency=["キズナ系", "エピファネイア系", "ドゥラメンテ系", "ロベルト系", "ハーツクライ系"],
        score_modifiers={
            "middle_distance": 3,
            "positioning": 3,
            "sustained_speed": 3,
            "hill_power": 3,
            "right_turn": 2,
            "late_speed_only": -2,
        },
    ),
    ("中山", "芝", 2200): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=2200,
        features=["外回り", "コーナーでの加速が重要", "ロングスパート戦になりやすい", "持続力型が向く"],
        favorable_styles=["先行", "好位差し", "まくり", "差し"],
        frame_bias="極端な枠差は少ないが、外を回す馬は早めに動ける持続力が必要。",
        required_abilities=["持続力", "ロングスパート", "急坂対応", "スタミナ", "右回り適性"],
        cautions=["瞬発力だけの馬、後方一気型、器用さに欠ける馬は割引。"],
        course_shape="中山芝2200m。外回りで長く脚を使う能力と坂対応を評価する。",
        pace_tendency="スローから平均が中心。向正面から徐々に動くロングスパート戦に注意。",
        closing_tendency="好位から早めに脚を使える馬、まくれる馬を評価。",
        suitable_types=["中山芝2200m実績馬", "ロングスパート型", "持続力型血統"],
        unsuitable_types=["瞬発力専用型", "後方一気型", "折り合い不安"],
        bloodline_tendency=["キタサンブラック系", "ハーツクライ系", "エピファネイア系", "ルーラーシップ系"],
        score_modifiers={
            "sustained_speed": 3,
            "long_spurt": 3,
            "stamina": 2,
            "hill_power": 2,
            "right_turn": 2,
            "late_speed_only": -2,
        },
    ),
    ("中山", "芝", 2500): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=2500,
        features=["内回り長距離", "有馬記念の舞台", "コーナー6回", "スタミナと立ち回りが重要"],
        favorable_styles=["先行", "好位差し", "まくり", "差し"],
        frame_bias="内から中枠を評価。外枠は距離ロスと位置取りに注意。",
        required_abilities=["スタミナ", "折り合い", "持続力", "立ち回り", "急坂対応", "ロングスパート"],
        cautions=["マイラー型、瞬発力だけの馬、外を回し続ける馬は割引。"],
        course_shape="中山芝2500m。コーナーが多く、スタミナ・折り合い・立ち回りが問われる。",
        pace_tendency="スローからロングスパート戦になりやすい。早めに動ける馬を評価。",
        closing_tendency="後方一気よりも、好位から長く脚を使える馬を評価。",
        suitable_types=["中山芝2500m実績馬", "有馬記念型", "スタミナ型", "まくり経験馬"],
        unsuitable_types=["距離不安の馬", "瞬発力だけの馬", "大箱専用型"],
        bloodline_tendency=["キタサンブラック系", "ハーツクライ系", "ステイゴールド系", "ロベルト系", "ルーラーシップ系"],
        score_modifiers={
            "stamina": 4,
            "positioning": 3,
            "sustained_speed": 3,
            "folding": 2,
            "hill_power": 2,
            "outside_draw": -1,
        },
    ),
    ("中山", "芝", 3600): CourseProfile(
        racecourse="中山",
        surface="芝",
        distance=3600,
        features=["超長距離", "ステイヤーズSの舞台", "スタミナ最重要", "折り合いと持続力が結果を左右"],
        favorable_styles=["先行", "好位差し", "まくり", "差し"],
        frame_bias="大きな枠差は少ないが、距離ロスを抑えられる内から中枠を微加点。",
        required_abilities=["スタミナ", "長距離適性", "折り合い", "持続力", "精神力", "急坂対応"],
        cautions=["短距離血統、折り合い難、スタミナ不明、瞬発力だけの馬は大きく割引。"],
        course_shape="中山芝3600m。超長距離戦でスタミナと折り合いを最優先で評価する。",
        pace_tendency="超スローからのロングスパートになりやすい。",
        closing_tendency="最後まで止まらない持続力と長距離実績を評価。",
        suitable_types=["3000m以上実績馬", "ステイヤー型", "折り合える馬", "スタミナ型血統"],
        unsuitable_types=["短距離型", "掛かる馬", "距離不安の馬"],
        bloodline_tendency=["ハーツクライ系", "ステイゴールド系", "キタサンブラック系", "ロベルト系"],
        score_modifiers={
            "stamina": 5,
            "distance_fit": 4,
            "folding": 3,
            "sustained_speed": 3,
            "hill_power": 2,
            "speed_only": -3,
        },
    ),
    ("中山", "ダート", 1200): CourseProfile(
        racecourse="中山",
        surface="ダート",
        distance=1200,
        features=["短距離ダート", "スタート後は下り", "テンの速さが重要", "最後に急坂"],
        favorable_styles=["逃げ", "先行", "好位差し"],
        frame_bias="外枠を評価。外からスムーズに先行できる馬が有利になりやすい。",
        required_abilities=["テンの速さ", "ダッシュ力", "先行力", "ダートスピード", "急坂対応"],
        cautions=["二の脚が遅い馬、追込一辺倒、砂をかぶると脆い馬は割引。"],
        course_shape="中山ダート1200m。下りでスピードに乗り、最後の急坂を踏ん張る短距離戦。",
        pace_tendency="ハイペースになりやすい。前残りが基本だが、消耗戦なら差しも浮上。",
        closing_tendency="逃げ・先行を評価。ハイペース時は坂で止まらない好位差しを評価。",
        suitable_types=["ダート1200m実績馬", "テンが速い馬", "外枠から先行できる馬"],
        unsuitable_types=["追走力不足", "後方一気型", "坂で甘くなる馬"],
        bloodline_tendency=["ヘニーヒューズ系", "シニスターミニスター系", "パイロ系", "サウスヴィグラス系"],
        score_modifiers={
            "early_speed": 4,
            "dirt_speed": 3,
            "outside_draw": 2,
            "hill_power": 2,
            "front_runner": 2,
            "late_speed_only": -2,
        },
    ),
    ("中山", "ダート", 1800): CourseProfile(
        racecourse="中山",
        surface="ダート",
        distance=1800,
        features=["コーナー4回", "急坂あり", "先行力と持続力が重要", "パワー型が向く"],
        favorable_styles=["先行", "好位差し", "逃げ", "まくり"],
        frame_bias="内から中枠を評価。外枠は早めに位置を取れる馬なら対応可能。",
        required_abilities=["先行力", "持続力", "パワー", "コーナリング", "急坂対応", "右回り適性"],
        cautions=["後方一気、小回りで動けない馬、砂をかぶると脆い馬は割引。"],
        course_shape="中山ダート1800m。コーナー4回と急坂で、先行力・持続力・パワーが問われる。",
        pace_tendency="平均ペースが中心。先行争いが激しいと差しも届くが、基本は前目を評価。",
        closing_tendency="直線だけより、早めに動いて坂で踏ん張る馬を評価。",
        suitable_types=["中山ダート1800m実績馬", "先行力がある馬", "パワー型血統", "まくり経験馬"],
        unsuitable_types=["後方一気型", "軽いダート専用型", "コーナーで置かれる馬"],
        bloodline_tendency=["ホッコータルマエ系", "シニスターミニスター系", "ドレフォン系", "ゴールドアリュール系"],
        score_modifiers={
            "positioning": 3,
            "sustained_speed": 3,
            "dirt_power": 3,
            "cornering": 2,
            "hill_power": 2,
            "late_speed_only": -2,
        },
    ),
    ("中山", "ダート", 2400): CourseProfile(
        racecourse="中山",
        surface="ダート",
        distance=2400,
        features=["長距離ダート", "スタミナ戦", "コーナーが多い", "位置取りと持続力が重要"],
        favorable_styles=["先行", "まくり", "好位差し", "差し"],
        frame_bias="内から中枠を微加点。外枠は距離ロスを抑える立ち回りが必要。",
        required_abilities=["スタミナ", "持続力", "パワー", "折り合い", "ロングスパート", "急坂対応"],
        cautions=["距離不安、短距離型、追込一辺倒、折り合い難は割引。"],
        course_shape="中山ダート2400m。長距離ダートでスタミナと持続力が問われる。",
        pace_tendency="スローから平均が中心。向正面からのロングスパート戦になりやすい。",
        closing_tendency="早めに動ける先行・まくり型を評価。",
        suitable_types=["ダート2400m実績馬", "長距離ダート実績馬", "スタミナ型", "まくり経験馬"],
        unsuitable_types=["距離不安", "短距離型", "後方一気型"],
        bloodline_tendency=["ホッコータルマエ系", "シニスターミニスター系", "ルーラーシップ系", "ロベルト系"],
        score_modifiers={
            "stamina": 4,
            "distance_fit": 3,
            "sustained_speed": 3,
            "dirt_power": 2,
            "positioning": 2,
            "hill_power": 2,
        },
    ),
}


NAKAYAMA_COURSE_PROFILES.update(
    {
        ("中山", "芝", 1200): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=1200,
            features=[
                "外回りコースの向正面奥からスタート",
                "スタート直後から下り坂でスピードに乗りやすい",
                "3コーナーまでの距離が短く序盤の位置取りが重要",
                "4コーナーから直線入口で加速できる機動力が必要",
                "直線は短めで最後に急坂がある",
                "スピードだけでなく坂を踏ん張るパワーが必要",
            ],
            favorable_styles=["先行", "逃げ", "差し", "追込"],
            frame_bias="内枠はロスなく運びやすく、開幕週は内枠有利。外枠は序盤に脚を使わされやすいが、馬場悪化時は外差しも警戒。",
            required_abilities=["スタート性能", "先行力", "短距離スピード", "コーナリング", "急坂適性", "パワー", "スピード持続力"],
            cautions=["出遅れ癖、追込一辺倒、直線の長いコース向き、平坦専用のスピード馬、坂で止まる馬、位置を取れない差し馬は割引。"],
            course_shape="中山芝1200m。下りスタートから流れやすく、先行力・コーナリング・急坂を踏ん張るパワーを評価する。",
            pace_tendency="前半が速くなりやすい。ハイペースでは差しも浮上するが、極端な追込までは届きにくい。平均なら先行有利、スローなら逃げ・先行有利。",
            closing_tendency="逃げ先行が基本有利。開幕週や高速馬場では前残りが強く、馬場が荒れると外差しやパワー型が浮上する。",
            suitable_types=["先行力がある馬", "中山芝1200m実績馬", "小回り短距離が得意な馬", "坂で止まらない馬", "テンが速く4角で好位を取れる馬"],
            unsuitable_types=["出遅れ癖がある馬", "追込一辺倒", "直線の長いコース向き", "平坦専用のスピード馬", "坂で止まる馬", "位置を取れない差し馬"],
            bloodline_tendency=["ロードカナロア", "ビッグアーサー", "キンシャサノキセキ系", "ダイワメジャー系", "ミスタープロスペクター系", "サクラバクシンオー系"],
            score_modifiers={
                "early_speed": 3,
                "sprint_speed": 3,
                "cornering": 2,
                "hill_power": 3,
                "nakayama_record": 2,
                "inside_draw": 1,
                "late_speed": -1,
            },
        ),
        ("中山", "芝", 1600): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=1600,
            features=[
                "外回りコースの1コーナー横ポケットからスタート",
                "スタート後すぐに下り坂へ入る",
                "2コーナーまで距離が短く外枠はロスが出やすい",
                "外回りだが直線は短く最後に急坂がある",
                "東京マイルのような直線勝負ではなく位置取りと機動力が重要",
            ],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内〜中枠有利。外枠は序盤のロスが大きいが、先行力と折り合いがあれば対応可能。内枠の機動力型は加点。",
            required_abilities=["マイル適性", "先行力", "コーナリング", "機動力", "急坂適性", "持続力", "中山適性"],
            cautions=["東京マイル専用の瞬発力型、外枠で先行力が弱い馬、追込一辺倒、コーナーで加速できない馬、坂で甘くなる馬は割引。"],
            course_shape="中山芝1600m。外回りでも直線勝負になりにくく、内枠・位置取り・コーナリング・急坂適性を重視する。",
            pace_tendency="序盤から流れやすく平均〜ややハイペースになりやすい。ハイなら差し有利だが中団までにいる馬を評価、平均なら先行・差し互角、スローなら先行有利。",
            closing_tendency="4角で好位にいる馬が有利。差しも届くが、位置取りが悪すぎると届きにくい。",
            suitable_types=["中山芝1600m実績馬", "小回りマイルが得意な馬", "好位で運べる馬", "4角で加速できる馬", "坂で止まらない馬", "持続力型マイラー"],
            unsuitable_types=["東京マイル専用の瞬発力型", "外枠で先行力が弱い馬", "追込一辺倒", "コーナーで加速できない馬", "坂で甘くなる馬"],
            bloodline_tendency=["ダイワメジャー系", "ロードカナロア", "モーリス", "キズナ", "ドゥラメンテ系", "ロベルト系", "キングカメハメハ系"],
            score_modifiers={
                "mile_fit": 3,
                "positioning": 3,
                "cornering": 3,
                "hill_power": 3,
                "sustained_speed": 2,
                "nakayama_record": 2,
                "inside_draw": 2,
                "outside_draw": -1,
                "late_speed": -1,
            },
        ),
        ("中山", "芝", 1800): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=1800,
            features=[
                "スタンド前からスタート",
                "1コーナーまで距離があり隊列は決まりやすい",
                "内回りコースを使用",
                "コーナー4回で小回り適性が重要",
                "最後の直線は短く急坂がある",
                "瞬発力よりも機動力と持続力が問われる",
            ],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内〜中枠が立ち回りやすい。外枠はコーナーでロスが出やすく、多頭数では外々を回される馬を割引。内枠の先行馬は加点。",
            required_abilities=["小回り適性", "コーナリング", "機動力", "持続力", "急坂適性", "中距離寄りのスタミナ", "位置取り能力"],
            cautions=["東京向きの瞬発力型、追込一辺倒、コーナリングが苦手な馬、直線が長いコースでしか好走していない馬、坂で失速する馬は割引。"],
            course_shape="中山芝1800m。内回りのコーナー4回戦であり、先行力・機動力・持続力・急坂適性を総合評価する。",
            pace_tendency="スロー〜平均ペースになりやすい。ハイでは差しも浮上するが早めに動ける差し馬を評価、平均なら先行・差し互角、スローなら先行・機動力型有利。",
            closing_tendency="向正面から徐々にペースアップしやすく、4角で前にいる馬が有利。直線一気は決まりにくい。",
            suitable_types=["中山芝1800m実績馬", "小回り1800mが得意な馬", "先行して長く脚を使える馬", "4角で動ける馬", "坂で止まらない馬", "中距離型の持続力馬"],
            unsuitable_types=["東京向きの瞬発力型", "追込一辺倒", "コーナリングが苦手な馬", "直線が長いコースでしか好走していない馬", "坂で失速する馬"],
            bloodline_tendency=["キズナ", "モーリス", "エピファネイア", "ドゥラメンテ系", "ハーツクライ系", "ロベルト系", "ステイゴールド系", "キングカメハメハ系"],
            score_modifiers={
                "cornering": 3,
                "positioning": 3,
                "sustained_speed": 3,
                "hill_power": 3,
                "middle_distance": 2,
                "nakayama_record": 2,
                "inside_draw": 1,
                "late_speed": -1,
            },
        ),
    }
)


NAKAYAMA_COURSE_PROFILES.update(
    {
        ("中山", "芝", 2000): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=2000,
            features=["4コーナー付近からスタート", "スタート直後に急坂", "1コーナーまで短い", "内枠有利", "コーナー4回", "機動力勝負"],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内有利。外枠は序盤ロスが出やすく、位置を取れない馬は割引。",
            required_abilities=["コーナリング", "位置取り", "急坂適性", "持続力", "中距離適性"],
            cautions=["東京専用瞬発型、追込一辺倒、外枠で位置が取れない馬は割引。"],
            course_shape="中山芝2000m。スタート直後から位置取りが重要になり、小回り・急坂・機動力を総合評価する。",
            pace_tendency="スロー〜平均になりやすい。ハイなら差し、平均なら先行、スローなら先行を評価。",
            closing_tendency="4角先頭集団が有利。差しは早め進出が必要で、直線だけでは届きにくい。",
            suitable_types=["中山実績馬", "小回り巧者", "先行持続型"],
            unsuitable_types=["東京専用瞬発型", "追込一辺倒", "外枠で位置が取れない馬"],
            bloodline_tendency=["キズナ", "モーリス", "エピファネイア", "ハーツクライ", "ステイゴールド系"],
            score_modifiers={
                "cornering": 3,
                "positioning": 3,
                "hill_power": 3,
                "middle_distance": 3,
                "nakayama_record": 2,
                "inside_draw": 2,
                "late_speed": -2,
            },
        ),
        ("中山", "芝", 2200): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=2200,
            features=["外回り使用", "スタミナ戦", "向正面からロングスパート"],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内〜中枠有利。外枠は早めに動ける持続力が必要。",
            required_abilities=["スタミナ", "持続力", "機動力", "急坂適性"],
            cautions=["瞬発力だけの馬は割引。"],
            course_shape="中山芝2200m。ロングスパート戦になりやすく、スタミナと持続力を重視する。",
            pace_tendency="平均からロングスパート戦になりやすい。ハイなら差し、平均なら先行、スローなら先行を評価。",
            closing_tendency="向正面から長く脚を使える馬を評価し、先行持続型を重視する。",
            suitable_types=["中距離〜長距離型", "先行持続型"],
            unsuitable_types=["瞬発力だけの馬"],
            bloodline_tendency=["ステイゴールド系", "キズナ", "エピファネイア", "ハーツクライ"],
            score_modifiers={
                "stamina": 3,
                "sustained_speed": 3,
                "cornering": 2,
                "hill_power": 2,
                "nakayama_record": 2,
            },
        ),
        ("中山", "芝", 2500): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=2500,
            features=["有馬記念コース", "スタンド前スタート", "コーナー6回", "総合力勝負"],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内有利。距離ロスを抑えて好位を取れる馬を評価。",
            required_abilities=["スタミナ", "折り合い", "機動力", "持続力"],
            cautions=["東京専用馬、折り合い難は割引。"],
            course_shape="中山芝2500m。有馬記念の舞台であり、スタミナ・機動力・急坂適性を総合評価する。",
            pace_tendency="平均からロングスパートになりやすい。平均なら総合力、スローなら機動力を評価。",
            closing_tendency="先行・差しを中心に、コーナー6回をロスなく運べる馬を評価。",
            suitable_types=["有馬記念好走型", "中山巧者"],
            unsuitable_types=["東京専用馬", "折り合い難"],
            bloodline_tendency=["ステイゴールド系", "キタサンブラック", "ハーツクライ", "ロベルト系"],
            score_modifiers={
                "stamina": 4,
                "cornering": 3,
                "hill_power": 3,
                "positioning": 2,
                "nakayama_record": 3,
            },
        ),
        ("中山", "芝", 3600): CourseProfile(
            racecourse="中山",
            surface="芝",
            distance=3600,
            features=["超長距離", "コーナー多数", "折り合い最重要"],
            favorable_styles=["先行", "差し", "追込", "逃げ"],
            frame_bias="内有利。長距離で距離ロスを抑えられる枠を評価。",
            required_abilities=["スタミナ", "折り合い", "持続力", "精神力"],
            cautions=["スピード型、掛かる馬は割引。"],
            course_shape="中山芝3600m。超長距離戦であり、折り合い・スタミナ・持続力を最優先で評価する。",
            pace_tendency="基本スローからロングスパート。時計が掛かるほどスタミナを重視する。",
            closing_tendency="重馬場では消耗戦になりやすく、長く脚を使える馬を評価。",
            suitable_types=["長距離巧者", "スタミナ型"],
            unsuitable_types=["スピード型", "掛かる馬"],
            bloodline_tendency=["ステイゴールド系", "ハーツクライ", "キタサンブラック", "ロベルト系"],
            score_modifiers={
                "stamina": 4,
                "distance_fit": 4,
                "sustained_speed": 3,
                "hill_power": 2,
            },
        ),
    }
)


NAKAYAMA_COURSE_PROFILES.update(
    {
        ("中山", "ダート", 1200): CourseProfile(
            racecourse="中山",
            surface="ダート",
            distance=1200,
            features=[
                "2コーナー奥のポケットからスタート",
                "スタート直後から下り坂でスピードに乗りやすい",
                "3コーナーまでの距離が短く、テンの速さが重要",
                "小回りでコーナリング性能が必要",
                "直線は短めだが最後に急坂がある",
                "スピードだけでなく坂を踏ん張るパワーも要求される",
            ],
            favorable_styles=["先行", "逃げ", "差し", "追込"],
            frame_bias="外枠有利。外枠は砂を被りにくくスムーズに加速しやすい。内枠は包まれるリスクがあるが、スタートが速い馬は割引しすぎない。",
            required_abilities=["テンの速さ", "ダート短距離スピード", "先行力", "コーナリング", "急坂適性", "パワー", "砂を被らない位置取り"],
            cautions=["出遅れ癖がある馬、追込一辺倒、テンに置かれる馬、平坦ダート専用のスピード馬、坂で止まる馬、内枠で砂を被ると嫌がる馬は割引。"],
            course_shape="中山ダート1200m。下りスタートから速く流れやすく、テンの速さ・外枠のスムーズさ・急坂を踏ん張るパワーを評価する。",
            pace_tendency="前半がかなり速くなりやすい。ハイでは差しも浮上するが極端な追込までは届きにくい。平均やスローなら逃げ・先行有利。",
            closing_tendency="基本は逃げ・先行有利。良馬場では先行力と持続力、脚抜きが良い馬場では高速先行決着への対応を評価。",
            suitable_types=["中山ダート1200m実績馬", "テンが速い馬", "小回りダート短距離巧者", "先行して坂で止まらない馬", "外枠からスムーズに運べる馬", "短距離ダートの持続型"],
            unsuitable_types=["出遅れ癖がある馬", "追込一辺倒", "テンに置かれる馬", "平坦ダート専用のスピード馬", "坂で止まる馬", "内枠で砂を被ると嫌がる馬"],
            bloodline_tendency=["ヘニーヒューズ", "シニスターミニスター", "サウスヴィグラス系", "パイロ", "ロードカナロア", "キンシャサノキセキ系"],
            score_modifiers={
                "early_speed": 4,
                "dirt_speed": 3,
                "cornering": 2,
                "hill_power": 3,
                "outside_draw": 2,
                "nakayama_record": 2,
                "sustained_speed": 2,
                "late_speed": -1,
            },
        ),
        ("中山", "ダート", 1800): CourseProfile(
            racecourse="中山",
            surface="ダート",
            distance=1800,
            features=[
                "スタンド前直線入口付近からスタート",
                "スタート直後に急坂を上る",
                "1コーナーまで距離があり隊列は決まりやすい",
                "コーナー4回の小回りダート",
                "向正面から徐々にペースが上がりやすい",
                "最後の直線は短く急坂がある",
                "位置取り、持続力、パワーが重要",
            ],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内〜中枠が立ち回りやすい。外枠は1コーナーまでに位置を取れないとロスが大きいが、先行力があれば対応可能。",
            required_abilities=["先行力", "位置取り能力", "コーナリング", "ダート中距離適性", "持続力", "急坂適性", "パワー", "スタミナ"],
            cautions=["東京ダート1600m専用のワンターン型、追込一辺倒、コーナー4回が苦手な馬、平坦ダート専用馬、直線が長いコースでしか差せない馬、スタミナ不安がある馬は割引。"],
            course_shape="中山ダート1800m。小回り4角の中距離ダートであり、位置取り・コーナリング・持続力・急坂を踏ん張るパワーを重視する。",
            pace_tendency="スロー〜平均ペースになりやすい。ハイでは早めに動ける差し、平均では先行・差し互角、スローでは先行・逃げを評価。",
            closing_tendency="向正面からロングスパートになりやすく、4角で前にいる馬が有利。差し馬は早めに動けるタイプを評価。",
            suitable_types=["中山ダート1800m実績馬", "小回りダート巧者", "先行して長く脚を使える馬", "4角で好位にいられる馬", "パワー型ダート馬", "坂で止まらない馬", "1800mで安定している馬"],
            unsuitable_types=["東京ダート1600m専用のワンターン型", "追込一辺倒", "コーナー4回が苦手な馬", "平坦ダート専用馬", "直線が長いコースでしか差せない馬", "スタミナ不安がある馬"],
            bloodline_tendency=["シニスターミニスター", "ホッコータルマエ", "ドレフォン", "ヘニーヒューズ", "ゴールドアリュール系", "キングカメハメハ系", "ロベルト系"],
            score_modifiers={
                "positioning": 3,
                "cornering": 3,
                "sustained_speed": 3,
                "hill_power": 3,
                "dirt_power": 3,
                "middle_distance": 2,
                "nakayama_record": 2,
                "inside_draw": 1,
                "late_speed": -1,
            },
        ),
        ("中山", "ダート", 2400): CourseProfile(
            racecourse="中山",
            surface="ダート",
            distance=2400,
            features=[
                "スタンド前からスタート",
                "ダート長距離戦",
                "コーナーを複数回通るため距離ロスが大きく影響する",
                "序盤は落ち着きやすい",
                "向正面からロングスパートになりやすい",
                "最後の直線は短く急坂がある",
                "スタミナ、折り合い、持続力、パワーが重要",
            ],
            favorable_styles=["先行", "差し", "逃げ", "追込"],
            frame_bias="内〜中枠有利。内枠は距離ロスを抑えやすく、外枠はコーナーでロスが増えやすい。外枠でも早めに位置を取れれば対応可能。",
            required_abilities=["スタミナ", "長距離ダート適性", "折り合い", "持続力", "コーナリング", "急坂適性", "パワー", "位置取り能力"],
            cautions=["短距離ダート型、1800mまでしか実績がない馬、瞬発力だけのタイプ、追込一辺倒、折り合いに難がある馬、距離延長でスタミナ不安がある馬、外々を回されそうな馬は割引。"],
            course_shape="中山ダート2400m。長距離ダート戦であり、スタミナ・距離適性・持続力・位置取り・急坂適性を総合評価する。",
            pace_tendency="スロー〜平均ペースになりやすい。ハイではスタミナ勝負、平均では先行・差しの総合力勝負、スローではロングスパート性能と位置取りを評価。",
            closing_tendency="向正面から徐々にペースアップし、早めに動ける先行馬が有利。差し馬は長く脚を使えるタイプを評価し、瞬発力だけでは届きにくい。",
            suitable_types=["中山ダート2400m実績馬", "2100m以上で好走歴がある馬", "スタミナ型ダート馬", "ロングスパート型", "早めに動いても止まらない馬", "パワー型", "内〜中枠でロスなく運べる馬"],
            unsuitable_types=["短距離ダート型", "1800mまでしか実績がない馬", "瞬発力だけのタイプ", "追込一辺倒", "折り合いに難がある馬", "距離延長でスタミナ不安がある馬", "外々を回されそうな馬"],
            bloodline_tendency=["シニスターミニスター", "ホッコータルマエ", "ゴールドアリュール系", "キングカメハメハ系", "ロベルト系", "キズナ（ダート型）", "ルーラーシップ"],
            score_modifiers={
                "stamina": 4,
                "distance_fit": 4,
                "sustained_speed": 3,
                "positioning": 3,
                "cornering": 2,
                "hill_power": 3,
                "dirt_power": 3,
                "nakayama_record": 2,
                "inside_draw": 1,
                "late_speed": -1,
            },
        ),
    }
)


NAKAYAMA_PACE_TRENDS = {
    "スロー": {
        "summary": "短い直線と急坂を考慮し、前目で運べる馬とロングスパート型を評価。",
        "favorable_styles": ["逃げ", "先行", "好位差し"],
        "required_abilities": ["位置取り", "折り合い", "急坂対応"],
    },
    "平均": {
        "summary": "立ち回りと持続力が結果に出やすい。",
        "favorable_styles": ["先行", "好位差し", "差し"],
        "required_abilities": ["持続力", "立ち回り", "パワー"],
    },
    "ハイ": {
        "summary": "消耗戦になりやすく、坂で止まらない差しやパワー型を評価。",
        "favorable_styles": ["好位差し", "差し", "まくり"],
        "required_abilities": ["消耗戦対応", "持続力", "急坂対応"],
    },
}


NAKAYAMA_FRAME_BIAS = {
    "芝1200": {"inner": 2, "middle": 2, "outer": 0, "comment": "内から中枠を評価し、外枠はテンの速さが必要。"},
    "芝1600": {"inner": 4, "middle": 2, "outer": -2, "comment": "外回りマイルは内枠と位置取りを評価。"},
    "芝中距離": {"inner": 3, "middle": 2, "outer": -1, "comment": "コーナー4回では距離ロスを抑える枠を評価。"},
    "ダート1200": {"inner": 0, "middle": 1, "outer": 3, "comment": "外枠からスムーズに先行できる馬を評価。"},
    "ダート中距離": {"inner": 2, "middle": 2, "outer": 0, "comment": "距離ロスを抑えつつ先行できる枠を評価。"},
}


NAKAYAMA_SEASONAL_BIAS = {
    "開幕週": {"bias": ["内前有利", "高速馬場", "先行評価"], "comment": "開幕週は内枠と前目の馬を評価。"},
    "開催中盤": {"bias": ["総合力", "持続力"], "comment": "中盤は立ち回りと持続力を重視。"},
    "開催終盤": {"bias": ["馬場悪化", "パワー", "外差し"], "comment": "終盤はパワー型や差しの浮上に注意。"},
}


NAKAYAMA_TRACK_CONDITION_DETAILS = {
    "良": {
        "clock": "標準からやや速い",
        "bias": "位置取りと急坂対応を評価",
        "styles": ["逃げ", "先行", "好位差し"],
        "required_abilities": ["スピード", "立ち回り", "急坂対応"],
    },
    "稍重": {
        "clock": "やや時計が掛かる",
        "bias": "持続力とパワーを加点",
        "styles": ["先行", "好位差し", "差し"],
        "required_abilities": ["持続力", "パワー", "馬場適性"],
    },
    "重": {
        "clock": "時計が掛かりやすい",
        "bias": "パワー型と前で運べる馬を評価",
        "styles": ["逃げ", "先行", "好位差し"],
        "required_abilities": ["パワー", "スタミナ", "急坂対応"],
    },
    "不良": {
        "clock": "消耗戦または前残りに振れやすい",
        "bias": "当日バイアスを最優先",
        "styles": ["逃げ", "先行", "まくり"],
        "required_abilities": ["道悪適性", "パワー", "持続力"],
    },
}


NAKAYAMA_BLOODLINE_COMPATIBILITY = {
    "得意": ["キズナ", "エピファネイア", "キタサンブラック", "モーリス", "ドゥラメンテ", "ハーツクライ", "ルーラーシップ"],
    "短距離向き": ["ロードカナロア", "ダイワメジャー", "ミッキーアイル", "ヘニーヒューズ"],
    "ダート向き": ["シニスターミニスター", "ホッコータルマエ", "ドレフォン", "パイロ", "ゴールドアリュール系"],
    "苦手注意": ["東京外回り専用型", "平坦専用スピード型", "瞬発力だけの血統"],
}


NAKAYAMA_MODIFIER_REASON_TEXT = {
    "early_speed": "スタート直後から流れに乗るためのテンの速さを評価",
    "sprint_speed": "芝1200mで必要な短距離スピードを評価",
    "sustained_speed": "速い流れやロングスパートで長く脚を使える持続力を評価",
    "hill_power": "中山直線の急坂を踏ん張る力を評価",
    "nakayama_record": "中山コース実績を評価",
    "right_turn": "中山の右回り適性を評価",
    "inside_draw": "内〜中枠は距離ロスを抑えやすい",
    "outside_draw": "外枠からスムーズに運べる条件を評価",
    "late_speed": "後方一気だけでは届きにくいため過大評価しない",
    "positioning": "4角で好位を取れる位置取り能力を評価",
    "mile_fit": "中山芝1600mへのマイル適性を評価",
    "cornering": "小回りや複数コーナーをロスなく回る能力を評価",
    "late_speed_only": "瞬発力だけでは中山で評価しすぎない",
    "middle_distance": "中山中距離への距離適性を評価",
    "long_spurt": "早めに動いて長く脚を使う能力を評価",
    "stamina": "長距離や急坂で必要なスタミナを評価",
    "folding": "長距離で折り合える能力を評価",
    "distance_fit": "長めの距離への適性を評価",
    "speed_only": "スピードだけのタイプは割引",
    "dirt_speed": "ダート1200mとしての基礎スピードを評価",
    "front_runner": "前で運べる脚質を評価",
    "dirt_power": "力の要る中山ダートでのパワーを評価",
}


NAKAYAMA_SCORE_MODIFIER_REASONS = {
    course_key: {
        modifier_name: {
            "score": score,
            "reason": NAKAYAMA_MODIFIER_REASON_TEXT.get(
                modifier_name,
                f"中山{course_key[1]}{course_key[2]}mの教科書に基づく補正。",
            ),
        }
        for modifier_name, score in profile.score_modifiers.items()
    }
    for course_key, profile in NAKAYAMA_COURSE_PROFILES.items()
}


NAKAYAMA_EXPLAIN_COMMENTS = [
    "中山は右回り・短い直線・急坂が特徴で、位置取り、立ち回り、持続力、坂対応を重視する。",
    "中山芝1200mは下りスタートから流れやすく、先行力・コーナリング・急坂を踏ん張るパワーを評価する。",
    "中山芝1600mは外回りでも直線勝負になりにくく、内枠・位置取り・コーナリング・急坂適性を重視する。",
    "中山芝1800mは内回りのコーナー4回戦であり、先行力・機動力・持続力・急坂適性を総合評価する。",
    "中山芝2000mはスタート直後から位置取りが重要になり、小回り・急坂・機動力を総合評価する。",
    "中山芝2200mはロングスパート戦になりやすく、スタミナと持続力を重視する。",
    "中山芝2500mは有馬記念の舞台であり、スタミナ・機動力・急坂適性を総合評価する。",
    "中山芝3600mは超長距離戦であり、折り合い・スタミナ・持続力を最優先で評価する。",
    "中山ダート1200mは下りスタートから速く流れやすく、テンの速さ・外枠のスムーズさ・急坂を踏ん張るパワーを評価する。",
    "中山ダート1800mは小回り4角の中距離ダートであり、位置取り・コーナリング・持続力・急坂を踏ん張るパワーを重視する。",
    "中山ダート2400mは長距離ダート戦であり、スタミナ・距離適性・持続力・位置取り・急坂適性を総合評価する。",
]
